#!/usr/bin/env groovy

def gitRepo = 'https://github.com/caichao1103/protobuf-ue4.git'

pipeline {
    agent {
        label "os:mac && thirdparty"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'PROTOBUF_UE4_VERSION',
            defaultValue: '3.19.4')
        string(name: 'IOS_DEPLOYMENT_TARGET',
            defaultValue: '12.0')
    }
    environment {
        PROTOBUF_UE4_VERSION             = "${params.PROTOBUF_UE4_VERSION}"
        PROTOBUF_UE4_PREFIX              = "${env.HOME}/thirdparty/protobuf-ue4/${params.PROTOBUF_UE4_VERSION}/ios"
        PROTOBUF_UE4_ZIP                 = "protobuf-ue4-${params.PROTOBUF_UE4_VERSION}-ios.zip"
        PROTOBUF_UE4_IOS_DEPLOYMENT_TARGET = "${params.IOS_DEPLOYMENT_TARGET}"
    }
    stages {
        stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        
        stage('Download') {
            steps {
                git url: gitRepo, branch: 'ios'
            }
        }
        
        stage('Build') {
            steps {
                withCMake('3.25.1') {
                    sh './Build_IOS.sh'
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.PROTOBUF_UE4_PREFIX, zipFile: env.PROTOBUF_UE4_ZIP
            }
        }
    }
}