#!/usr/bin/env groovy

import com.kingsoft.shiyou.UnrealEngineBuild

ueBuild = new UnrealEngineBuild(this)


pipeline {
    agent {
        label "linux-8"
    }
    options {
        skipDefaultCheckout()
    }
    parameters {
        string(name: 'PROTOBUF_UE4_VERSION', defaultValue: '3.19.4')
        string(name: 'MYCFLAGS', defaultValue: '')
        string(name: 'MYLDFLAGS', defaultValue: '')
        string(name: 'ENGINE_BRANCH', defaultValue: 'release')
        booleanParam(name: 'CLEAN_WS',
            defaultValue: true,
            description: 'When checked, call function cleanWs.')
    }
    environment {
        PROTOBUF_UE4_WORKSPACE           = "${env.WORKSPACE}"
        UE4_ROOT                         = "${env.WORKSPACE}/UnrealEngine"
        PROTOBUF_UE4_VERSION             = "${params.PROTOBUF_UE4_VERSION}"
        PROTOBUF_UE4_PREFIX              = "${env.HOME}/thirdparty/protobuf-ue4/${params.PROTOBUF_UE4_VERSION}/linux"
        PROTOBUF_UE4_ZIP                 = "protobuf-ue4-${params.PROTOBUF_UE4_VERSION}-linux.zip"
        UE4_CLANG_VERSION                = "v20_clang-13.0.1-centos7"
        UE4_ZLIB_VERSION                 = "v1.2.8"
        ENGINE_LOCAL_DIR                 = 'UnrealEngine'
        ENGINE_SYS                       = 'Linux'        
    }
    stages {
        stage('Cleanup') {
            steps {
                script {
                    if (params.CLEAN_WS) {
                        cleanWs()
                    }
                }
            }
        }

        stage('Checkout Out') {
            steps {
                checkout scm
            }
        }

        stage('Git Engine') {
            steps {
                script {
                    def ue4CleanBuild = !fileExists(ENGINE_LOCAL_DIR)
                    if (ue4CleanBuild) {
                        ueBuild.ueCheckout(ENGINE_LOCAL_DIR, ENGINE_SYS, params.ENGINE_BRANCH)
                        dir(ENGINE_LOCAL_DIR) {
                            buildEngine.ueSetup(ENGINE_SYS, '')
                        }
                    }
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('protobuf-ue4/linux') {
                    withCMake('3.12.2') {
                        sh 'rm -rf *.zip'
                        sh './Build_Linux.sh'
                    }
                }
            }
        }

        stage('Archive') {
            steps {
                zip archive: true, dir: env.PROTOBUF_UE4_PREFIX, zipFile: env.PROTOBUF_UE4_ZIP
            }
        }
    }
}